### ISSUE TITLE
Quest 3 - Post-Completion Dialogue

### ISSUE THREAD

**Issue by porkbob** [Kyuuhachi/Inevitable-Zero#2]
Haha, thought I was going to get through a quest without finding something. This is admittedly the most minor thing so far, but I guess I might as well report it, because I'm not sure if anyone else will.

Once you finish the 3rd Vita quest in Mishelam, if you go talk to Mishy, Randy has a line where he says "Even though he's supposed to saying thanks [etc]", and it's missing the word "be".

Maybe the next two quests I won't find anything, so while I still am posting here, might as well throw out that the old "patch" folder is still in the release even though it's empty. Obv not going to harm anything, but there ya go. Thanks again for porting these quests over!

**Comment by Kyuuhachi** [comment]
Small stuff, but fixed. Thanks for reporting.
